### ISSUE TITLE
Installer Chat Brevo

### ISSUE THREAD

**Issue by BenjaminSIP** [wellsy-organization/projects#1]
Installer chat Brevo sur le site d'Académie Aparté

Il faudra placer cette adresse de connexion  [contact@academie-aparte.com](mailto:contact@academie-aparte.com) & Académie aparté en nom de chat.

**Comment by louberady** [comment]
@BenjaminSIP 
J'ai fait la demande ce matin par mail au client. 🚀

**Comment by louberady** [comment]
Voici les accès à Brevo

Adresse mail : axel@academie-aparte.com
MDP : AparteBrevo2024*

**Comment by louberady** [comment]
Dispo à 9h30 demain pour le code de vérif ? Le client l'est et moi aussi :)

**Comment by BenjaminSIP** [comment]
Je serais en rdv toute la matinée, ça peut être à partir de 13h30

**Comment by louberady** [comment]
14h c'est bon pour toi ?

**Comment by BenjaminSIP** [comment]
Oui c'est bon

**Comment by louberady** [comment]
Il est en réunion à 14h, donc il me propose 18h00.

**Comment by BenjaminSIP** [comment]
Ok pas de soucis

**Comment by louberady** [comment]
Le client propose demain 9h30-10h ou 11h30-12h ou entre 18h-18h45. 
Tu serais dispo sur un des 3 créneaux ? Je propose de vérifier la dispo du client avant de te solliciter demain (comme j'ai fait à 18h00 ce jour).

**Comment by BenjaminSIP** [comment]
Je suis dispo à tous ces créneaux

**Comment by louberady** [comment]
Hello 
Es tu dispo ?

**Comment by BenjaminSIP** [comment]
**Reste à faire de votre côté :**
Retirer l'ancien widget de contact
Passer le widget Captcha à gauche

**Comment by louberady** [comment]
Le sujet des mails sortant est optimisé aussi ? Je ne sais plus le terme exact. :)
