### ISSUE TITLE
Barre de recherche - demandes supp

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#10]
1-Peux tu regarder la responsive mobile de la barre de recherche, perso je n’ai pas vu de problématique sur safari.
2-Le client voudrait switcher le bloc Propriété par villes avec le bloc Nos biens d’exceptions sur la HP (FR + ENG).

3-Sur les pages du menu vertical Location
   1-https://global-luxury-properties.com/location/ => à appliquer le filtre « Location » par défaut : ✅  cf. PJ : Location est bien par défaut 
   2-https://global-luxury-properties.com/location-villa-luxe-cannes/ =>  à appliquer le filtre « Location » par défaut + intégrer la ville de Cannes par défaut si possible
   3-https://global-luxury-properties.com/location-villa-luxe-saint-tropez/ => à appliquer le filtre « Location » par défaut + intégrer la ville de St Tropez par défaut si possible

:Capture d’écran 2024-08-05 à 18.43.38.png
 

4-Sur les pages du menu vertical Transaction
   1-https://global-luxury-properties.com/transaction/  => à appliquer le filtre « Vente » par défaut : fait ✅  cf. PJ : Vente est bien par défaut
   2-https://global-luxury-properties.com/villa-luxe-cannes/  => à appliquer le filtre « Vente » par défaut + intégrer la ville de Cannes par défaut si possible
   3-https://global-luxury-properties.com/villa-luxe-saint-tropez/  => à appliquer le filtre « Vente » par défaut + intégrer la ville de St Tropez par défaut si possible
Capture d’écran 2024-08-05 à 19.31.50.png

+ demande antérieure
=> intégrer la barre de recherche sur toutes les pages accessibles via le menu principal

**Comment by BenjaminSIP** [comment]
Pour être sûr qu'on attende bien la même chose, on est en attente de la validation du client c'est ça ?
Car normalement tout à bien été fait par rapport à ces dernières modifs
