### ISSUE TITLE
Widgets à retirer / Déplacer (suite Brevo)

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#19]
- Retirer l'ancien widget de contact
- Passer le widget Captcha à gauche
- Passer l'icône "Back to top" à gauche

**Comment by BenjaminSIP** [comment]
@louberady est-ce que tu sais où a été paramétre le captcha ?
À priori ce n'est pas via formidable forms

**Comment by BenjaminSIP** [comment]
C'est bon je l'ai trouvé
