### ISSUE TITLE
Académie aparté - 8 points 

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#25]
1- Problème le plus urgent : est ce que le site se serait fait hacké ? de mon côté je ne vois pas cet écran mais le client oui :/
<img width="664" alt="Capture d’écran 2024-09-16 à 16 37 50" src="https://github.com/user-attachments/assets/23f72669-00c3-4c6d-bba3-b69eee929d93">
<img width="743" alt="Capture d’écran 2024-09-16 à 16 37 58" src="https://github.com/user-attachments/assets/28d13321-a1e8-4079-b320-000284ab8dd7">

2- Sur Firefox (uniquement? en tout cas ce problème n'est pas présent via Google Chrome) 
À droite il y a un problème de dimension (voir flèche et encadré):
<img width="640" alt="Capture d’écran 2024-09-06 à 11 13 42" src="https://github.com/user-attachments/assets/68572c65-4579-44b4-82f3-831c4fe5765d">

3-Sur Firefox (uniquement? en tout cas ce problème n'est pas présent via Google Chrome) 
les liens sur l’image de la home
Les formations en entreprises 
Les stages fadas et 
Les masterclass ne sont pas cliquables (encadrés en bleu ici ⬇️)
<img width="640" alt="Capture d’écran 2024-09-06 à 11 12 14" src="https://github.com/user-attachments/assets/0c28cd2d-064a-4670-a3c8-2f616f60d107">

4-Sur tous les navigateurs
Lorsque tu clique sur L’école, ça l’ouvre dans un nouvel onglet, ce qui nest pas normal.
<img width="635" alt="Capture d’écran 2024-09-16 à 16 44 47" src="https://github.com/user-attachments/assets/ad53fef3-42ce-4c5b-aff4-820597b68052">

5- Sur tous les navigateurs 
En dessous de la ligne de flottaison sur la Home : il est écrit «  Sticky buttons id=1 ».

6- Pour le pluggin de chat Brevo, il faut changer la couleur du picto (voir flèche)
Ils veulent la passer en jaune : Couleur #F4C060 

7-Demande de la cliente : je ne parviens pas à accéder à médiathèque dans l'admin que ce soit via le menu Media > Médiathèque ou bien lors de la modification d'une page pour insérer une image via Elementor.
C'est assez génant. Est-ce que ca fait ca chez vous aussi ?

8- Au global la vitesse de chargement n’est pas bonne du tout 
Sur Mobile + Bureau 
https://pagespeed.web.dev/analysis/https-academie-aparte-com/cc0wbgioa0?hl=fr&form_factor=desktop

**Comment by BenjaminSIP** [comment]
1- Comme vu ensemble, en attente des accès FTP, après il faudrait aussi savoir sur quoi le client clique, ou bien quelle adresse URL il tape exactement dans son navigateur, car idem pas de soucis de mon côté, cela peut être dû à une de ses extensions qu'il utilise, tu pourrais lui demander s'il a le même souci depuis un autre navigateur. Même si c'est vrai que ça ressemble à un malware en effet, à vérifier une fois qu'on récupère les accès FTP

2- Corrigé

3- @thomas-ddev est-ce que tu pourrais effectuer ce point stp ?

4- @thomas-ddev est-ce que tu pourrais effectuer ce point stp ?

5- Corrigé

6- Corrigé

7- Il y a une erreur 500 dans la console lors du chargement de la médiathèque, le serveur ne doit pas avoir de ressources suffisantes, si vous pouvez nous envoyer les codes d'accès à l'hébergement ?

8- Je propose que l'on s'en occupe après avoir traité le point 1 car il permettra certainement d'améliorer déjà un peu les performances, puis ensuite on affinera une fois que le site sera remis au propre

**Comment by louberady** [comment]
Voici les accès OVH
ID: bl210353-ovh
Catchpitch01!

![Image](https://github.com/user-attachments/assets/40a506fb-8f79-4fe7-bf01-a53259387cca)

**Comment by BenjaminSIP** [comment]
**Nouveaux accès FTP :**
serveur : ftp.cluster027.hosting.ovh.net
login : academl
port ftp : 21
mot de passe : StAgq6a7jhQ

**Comment by BenjaminSIP** [comment]
**État à jour :**
1- Corrigé

2- Corrigé

3- Corrigé par la cliente

4- Corrigé par la cliente

5- Corrigé

6- Corrigé

7- Corrigé

8- 
**Anciens résultats :**
Bureau - 56
Mobile - 26

**Nouveaux résultats :**
Bureau - 96
Mobile - 68

**Comment by louberady** [comment]
La cliente peut elle appliquer des optimisations pour améliorer le chargement mobile ?

**Comment by BenjaminSIP** [comment]
Lesquelles ?

**Comment by louberady** [comment]
je sais pas justement, mais elle a été sur PSI et elle a remarqué que sur mobile on était en "orange". ahah

**Comment by louberady** [comment]
+ Sur la page d'acceuil, il semble y avoir encore un problème en accédant au site via les SERP (je sais pas si ça a un rapport avec ce que tu disait tout à l'heure sur WA)
+ Sur le back office, la cliente essaie de résoudre le problème mais ça plante pas mal
![Image](https://github.com/user-attachments/assets/802daca2-6547-4eb0-9c6d-4f936e6bfe6e)
+ J'arrive pas à me déconnecter (mon ordi semblait être connecté au BO) ça donne ça :
![Image](https://github.com/user-attachments/assets/59914be6-86f6-4e99-a068-536c09420868)

**Comment by BenjaminSIP** [comment]
1) Si possible d'avoir plus d'infos car le problème n'existe plus de mon côté

2) Quel problème ?

3) Je regarde

**Comment by BenjaminSIP** [comment]
1. Si possible d'avoir plus d'infos car le problème n'existe plus de mon côté
2. On voit une erreur 403 sur le screen, ce qui est une erreur d'autorisation, est-ce que tu peux lui demander :
Avec quel compte elle est connectée ?
Quelle action **exactement** génère cette erreur ?
3. Peux-tu réessayer et me dire si tu as toujours l'erreur ?

**Comment by BenjaminSIP** [comment]
Si les 8 points sont bien validés de ton côté si possible de clore cette issue et d'en créer une nouvelle si besoin

**Comment by louberady** [comment]
il semble y avoir toujours un problème de hack quand j'accède a academie via les SERP je tombe sur un ecran qui mindique de patienter puis il me redirige vers un lien : 
![Image](https://github.com/user-attachments/assets/ec3c2203-88a5-42b2-873a-4aafcb989e29)

**Comment by louberady** [comment]
@BenjaminSIP Peux tu regarder si c'est un problème demande une action de ta part ?
Dois je lui indiquer de vider son cache ? 
De mon côté je n'ai pas ce problème. 

![Image](https://github.com/user-attachments/assets/69698f36-da95-42c5-bca8-429fd3dc75a6)

**Comment by BenjaminSIP** [comment]
Ce message de la cliente datait d'hier je pense.
On a recorrigé un max de fichiers corrompus hier et j'ai réinstallé la protection de pare-feu avancé de WordFence (plugin de sécurité). Le virus avait dû la faire sauter car les malwares modifient justement les fichiers notamment le fichier htaccess où se trouve l'installation avancée de WordFence.

Cela m'étonnerait que cela revienne cette fois-ci. Si c'est le cas, on fera les mises à jours du thème et des add-ons du thème, ce qui est sensible à faire mais ce sera l'une des dernières choses que l'on pourra faire pour espérer corriger définitivement le problème
