### ISSUE TITLE
Problème technique & question

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#27]
1- Dans chacun des articles de blog, le bouton en bas de page "Back ton news" ne fonctionne pas correctement 
exemple : https://novaptech.com/en/novaptech-new-offices/ quand je clique dessus, je tombe sur la section BLOG version FR
soit cette URL : https://novaptech.com/fr/aptamer-news/

2- Question :  A quelle fréquence doit-on mettre le captcha à jour ? (la cliente a eu des commentaires venant de bots donc on a mis à jour le pluggin).

**Comment by BenjaminSIP** [comment]
1- Corrigé

2- Dès qu'une nouvelle mise à jour est disponible
