### ISSUE TITLE
Intégration de 2 nouvelles pages FR + leurs versions ENG

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#30]
Il faut créer 2 nouvelles pages, et leurs versions ENG 

[GLP - Location villa luxe Mougins - GO LAB.docx](https://github.com/user-attachments/files/17077085/GLP.-.Location.villa.luxe.Mougins.-.GO.LAB.docx)
[GLP - Luxury Villa Mougins - GO LAB.docx](https://github.com/user-attachments/files/17077088/GLP.-.Luxury.Villa.Mougins.-.GO.LAB.docx)
[GLP - Luxury villa Rentals Mougins - GO LAB.docx](https://github.com/user-attachments/files/17077089/GLP.-.Luxury.villa.Rentals.Mougins.-.GO.LAB.docx)
[GLP - Villa luxe Mougins - GO LAB.docx](https://github.com/user-attachments/files/17077090/GLP.-.Villa.luxe.Mougins.-.GO.LAB.docx)

1- Location Villa luxe Mougins **FR**
2- Luxury villa Rentals Mougins **ENG**

3-Villa luxe Mougins **FR**
4-Luxury Villa Mougins **ENG**

Les balises H1 sont précisées en haut de chaque doc, pour chacune des pages.

_PI, au vu des précédents sujets de problématiques avec les contenus qui n'étaient pas exactement les mêmes, j'ai cette fois précisé à l'auteur de bien être similaire entre les 2 versions de contenus pour qu'on ait 0 problématique avec les blocs de textes._ 

Accès BO :

https://global-luxury-properties.com/wp-login.php?
glp@global-luxury-properties.com
qr8Ch5N@SzasZovOQCOi75L8

**Comment by Kantin-digitalmarketing** [comment]
-Nouvelles pages en FR créées 
-Nouvelles images ajoutées pour éviter une redondance 
-Traductions EN faites
-Responsive fait
-J'ai changé les meta-titres et meta-descriptions pour que ça corresponde aussi aux pages

@louberady je te laisse vérifier et si tout est ok pour toi, je peux rajouter les deux pages dans le menu.

**Comment by louberady** [comment]
Super Kantin. Tout est good merci, tu peux ajouter les 2 pages au menu ;)
J'ai une question concernant le formulaire en bas de page, est normal qu'il soit écrit "VERMEESCH" soit le nom de famille du client dans le Nom cf. PJ
![Image](https://github.com/user-attachments/assets/989697c1-7ce3-4a9e-a537-0f801cdd2ee4)

**Comment by Kantin-digitalmarketing** [comment]
Salut Lou, nickel alors je met ça dans le menu ! 

Concernant le nom de famille du client qui apparait dans le formulaire, vu qu'il est en gris il sert juste d'exemple (comme pour "Cannes" dans le champ "ville"), pour moi il n'y a rien de choquant mais on a pas touché au formulaire lors de la création des pages SEO donc ça n'a pas été paramétré comme ça par nous. 

Tu en penses quoi @BenjaminSIP ?

**Comment by Kantin-digitalmarketing** [comment]
@louberady c'est rajouté dans le menu :)

**Comment by louberady** [comment]
Je ne savais pas que c'était déjà le cas avant. Laissons comme ça alors. Si le client me fais la réflexion, je vous demanderai le process pour modifier cela.
Merci :)

**Comment by BenjaminSIP** [comment]
Non ce n'est pas normal car même en étant pas connecté le placeholder Vermeesh qui est le nom de Victor apparaissait.

J'ai donc changé tous les placeholders de tous les formulaires du site ainsi dont les placeholders de ville, surface, budget, etc... pour que ce soit plus neutre
