### ISSUE TITLE
La sélection - assez urgent :)

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#31]
Problème sur le front de la cliente, une employée à ajouter des liens externes sur le site
Il semble qu'elle n'ait pas touché ni au header, ni au code, donc pas compréhensible.
Leur dév a check et n'a pas trouvé. 

Et ça a impacté toutes les pages du site :

<img width="1911" alt="Capture d’écran 2024-09-25 à 12 31 32" src="https://github.com/user-attachments/assets/73eaf660-4fb1-457d-b5cd-39ea185fad2b">

Accès :
https://accounts.shopify.com/login
l.berady@see-u-better.com
DhfjgDSh34!unv45

**Comment by BenjaminSIP** [comment]
@thomas-ddev si tu peux regarder cette issue en urgence please, merci

**Comment by thomas-ddev** [comment]
Il faudrait me partager le ZIP qui a été envoyé : 
![image](https://github.com/user-attachments/assets/36d628aa-e330-451f-885b-f9cb160c9307)

Ainsi que me donner éventuellement accès au GitHub, les modifications récentes si trouvent peut-être, ce qui pourrait aider à comprendre.

**Comment by thomas-ddev** [comment]
C'est potentiellement de la syntaxe ou une mise à jour du thème (je sais pas comment est géré le thème) : 

![image](https://github.com/user-attachments/assets/2769f2af-353f-4e70-9541-29b6175d20ba)


Avant ça ressemblait à : 
![image](https://github.com/user-attachments/assets/e02eb384-e74b-4138-832e-e389b70332c8)

**Comment by BenjaminSIP** [comment]
@louberady je te laisse répondre

1) tu as dû recevoir un zip par e-mail à l'adresse indiquée sur le screenshot de Thomas.

2) Si tu peux aussi demander au client d'inviter l'utilisateur thomas-ddev au GitHub de la sélection (on voit sur la capture de Thomas qu'un repository est en place pour le site, on donc peut-être y trouver l'historique des modifications)

**Comment by BenjaminSIP** [comment]
> C'est potentiellement de la syntaxe ou une mise à jour du thème (je sais pas comment est géré le thème) :
> 
> ![image](https://private-user-images.githubusercontent.com/18127378/370684273-2769f2af-353f-4e70-9541-29b6175d20ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjI1MzMsIm5iZiI6MTcyNzI2MjIzMywicGF0aCI6Ii8xODEyNzM3OC8zNzA2ODQyNzMtMjc2OWYyYWYtMzUzZi00ZTcwLTk1NDEtMjliNjE3NWQyMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDExMDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZGNiY2M3ZGQwZDkxYWQxOTRhNDliZjZhMzMxZGVmNzRhMzJkM2EzNTkxMzQ3ODI3NDMxOWJmMDYzYzZjM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SA4jmob4cHVyYyyBI2V9aNpW4yl_t6yYeMbPLvTzDyg)
> 
> Avant ça ressemblait à : ![image](https://private-user-images.githubusercontent.com/18127378/370684326-e02eb384-e74b-4138-832e-e389b70332c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjI1MzMsIm5iZiI6MTcyNzI2MjIzMywicGF0aCI6Ii8xODEyNzM3OC8zNzA2ODQzMjYtZTAyZWIzODQtZTc0Yi00MTM4LTgzMmUtZTM4OWI3MDMzMmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDExMDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNDIzYTZlNWMxZmQ2Nzc2MWIxODAzMTkwMzNkZTAxYjAwYjE3OWIyOWI3NDNlYzZiZjFhMDY3MWUzYmQzNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ommwb8Ffh48bc1JUr4hrm8YlUgDNQA-cKIQ-LwJg_6o)

C'est donc peut être une MAJ du thème, il n'y a pas de back up qu'on pourrait restorer sur Shopify ? (à ne pas faire tant qu'on a pas le go de principe de @louberady)

**Comment by louberady** [comment]
[theme_export__la-selection-fr-la-selection-main__25SEP2024-1255pm.zip](https://github.com/user-attachments/files/17130399/theme_export__la-selection-fr-la-selection-main__25SEP2024-1255pm.zip)

**Comment by louberady** [comment]
Je me renseigne pour :
2- Si tu peux aussi demander au client d'inviter l'utilisateur thomas-ddev au GitHub de la sélection (on voit sur la capture de Thomas qu'un repository est en place pour le site, on donc peut-être y trouver l'historique des modifications)

**Comment by thomas-ddev** [comment]
OK normalement j'ai pu corriger en bidouillant un peu le header, et la sidebar de droite refonctionne

**Comment by BenjaminSIP** [comment]
@louberady est-ce qu'il y a aussi le problème du footer à corriger ?

**Comment by louberady** [comment]
@BenjaminSIP Yes en effet, le footer est de travers :/

**Comment by BenjaminSIP** [comment]
@thomas-ddev si tu peux déjà corriger le z-index du footer + le mettre au bon endroit car lorsqu'on scroll tout en bas le footer reste au dessus des éléments

@louberady qu'est-ce que tu entends par "de travers" ?

**Comment by louberady** [comment]
Simplement qu'il y a un problème sur le footer, vous voyez la même chose que moi ?
1-Il est coupé
![Image](https://github.com/user-attachments/assets/c9b659d4-331d-4aaf-bf8e-54b64949f96f)
2-En scrollant vers le bas le footer reste très présent (je n'ai testé que sur la home)

**Comment by thomas-ddev** [comment]
> Simplement qu'il y a un problème sur le footer, vous voyez la même chose que moi ? 1-Il est coupé ![Image](https://private-user-images.githubusercontent.com/177762137/370724240-c9b659d4-331d-4aaf-bf8e-54b64949f96f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjk5MjIsIm5iZiI6MTcyNzI2OTYyMiwicGF0aCI6Ii8xNzc3NjIxMzcvMzcwNzI0MjQwLWM5YjY1OWQ0LTMzMWQtNGFhZi1iZjhlLTU0YjY0OTQ5Zjk2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzA3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjJlMzFhZmI0MDE3ZjZkZWQ2YTEwNmJiMzllMmI4MDQ2MWM3Mzc5MWZlMmQxZjRjMWNhMTRiNTAxYmM2NWVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Yj-oeBdnhhL8Dl_BLQIjtz5UFPwEok56-kpgOIfDWa0) 2-En scrollant vers le bas le footer reste très présent (je n'ai testé que sur la home)

Je vois bien ça de mon côté, mais est-ce qu'il était déjà "flottant" avant ? Et donc, toujours visible à l'écran ?

**Comment by louberady** [comment]
Parfait Merci !
La cliente vient de me répondre qu'il était visible en bas de page uniquement. :)

**Comment by louberady** [comment]
@thomas-ddev C'était donc dû au thème qui s'était mis à jour automatiquement ? 
Et donc tu as du passer par le code, c'est bien ça ?

**Comment by thomas-ddev** [comment]
> @thomas-ddev C'était donc dû au thème qui s'était mis à jour automatiquement ? Et donc tu as du passer par le code, c'est bien ça ?

Je ne peux pas l'affirmer avec certitute, n'ayant pas euaccès à tout l'historique des modifications du thème. Par contre, j'ai vu dans la liste des thèmes installés la toute première version du site et le code était complétement différent. Comme on était un peu dans l'urgence je n'ai pas creusé en profondeur, j'ai plutôt tenté de corriger directement le bug, dans le code, oui (une partie c'était la correction d'un template du thème, l'autre du design CSS)
