### ISSUE TITLE
Restauration de site

### ISSUE THREAD

**Issue by BenjaminSIP** [wellsy-organization/projects#32]
Il faudrait étudier la restauration d'un site à partir de fichiers de back up UpdraftPlus. Les ZIPs de back up se trouvent sur un Google Drive que je t'ai paratgé à l'adresse contact@thomasdubrez.fr
Il faut utiliser les derniers ZIP disponibles afin de restaurer la sauvegarde la plus récente.

Si possible de me faire une estimation tarifaire avant de commencer la restauration.

Le site a été supprimé donc il faut refaire l'installation de zéro.

Codes d'accès WP (anciens/nouveaux acccès) + Infomaniak :
[Infos-Comptes_maisonrougestudio.com 2.pdf](https://github.com/user-attachments/files/17131209/Infos-Comptes_maisonrougestudio.com.2.pdf)

**Comment by thomas-ddev** [comment]
Bah comme ça dur à dire, Updraft si il manque un seul zip, ça risque de foirer quelque chose. À part tenter de restaurer la backup via une nouvelle installation WP + le module UpDraft, on peut pas trop savoir derrière l'état du site après restauration. Donc pour ça faut minimum une heure, pour le reste on peut pas savoir avant.

**Comment by thomas-ddev** [comment]
L'ancien et le nouveau site ne sont pas accessibles, donc je suis allé sur Infomaniak, 0 site de configuré, pour configurer un site il faut payer : 
![image](https://github.com/user-attachments/assets/b7c4766f-2b5b-4ae2-a8e9-e7044aa55820)

**Comment by BenjaminSIP** [comment]
Oui c'est ce que j'avais indiqué "Le site a été supprimé donc il faut refaire l'installation de zéro."

Je vois 0/20, ça ne veut pas dire que l'on peut créer un site WP vierge déjà ?

Si pas possible, confirme moi et je demanderais au client de prendre un hébergement payant

**Comment by thomas-ddev** [comment]
Si exact, je regarde

**Comment by thomas-ddev** [comment]
Si possible de me dire quand le client reçoit le mail comme quoi c'est restauré

**Comment by BenjaminSIP** [comment]
Oui

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by BenjaminSIP** [comment]
@thomas-ddev Si tu peux augmenter les possibilités d'upload sur le site.

CF. message d'erreur lors de l'upload des back up de plus de 500mo sur updraftplus :
<img width="413" alt="Capture d’écran 2024-10-04 à 09 41 34" src="https://github.com/user-attachments/assets/72ac0f1e-6c17-4f60-9774-ca26a6a6429d">

**Comment by thomas-ddev** [comment]
OK, passé de 300 a 1024M

**Comment by BenjaminSIP** [comment]
Il ne reste plus qu'un fichier qui est encore bloquant lors de l'upload ([pièce-jointe](https://drive.google.com/file/d/1_uBWlNXiZF1QYkvde_cOultPm4aLcFQ-/view?usp=drive_link)) c'est celui qui est le plus volumineux, j'ai aussi augmenter les limites côté infomaniak jusqu'à 13h47.

Tu as accès au fichier Drive avec l'adresse contact@thomasdubrez.fr

Si tu peux augmenter d'autre règles qui empêcheraient l'upload, peut être le timeout, vérifier si la RAM pose soucis ou autre, et en priorité, juste augmenter les autres limitations classiques depuis le htaccess/php.ini/wp-congig.php dans un premier temps

**Comment by thomas-ddev** [comment]
WP CONFIG: 
ini_set('max_execution_time', 0); // 0 means unlimited
define('WP_MEMORY_LIMIT', '2048M'); // Set the desired memory limit, e.g., 1GB
define('WP_MAX_MEMORY_LIMIT', '4096M'); // Set higher for admin tasks (e.g., 2GB)

Et côté serveur : 
![image](https://github.com/user-attachments/assets/c8114fe8-8630-4541-845d-a0ef8770790d)

Ça a été débloqué récemment visiblement on ne peut pas aller au delà

**Comment by BenjaminSIP** [comment]
Je t'ai mis le lien du dernier fichier à importer, si tu peux tester stp, car de mon côté ce n'est toujours pas bon mais cela peut être dû à ma connexion qui saute car j'ai vu une erreur de changement de réseau dans le network à plusieurs reprises

**Comment by BenjaminSIP** [comment]
Super merci !
