### ISSUE TITLE
Vidéo sur HP 

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#34]
Sur la page d'acceuil, le client souhaite que la video ne se lance pas immédiatement afin de voir le message s'afficher plus longtemps et de façon plus claire.

Accès 
http://www.canal33.fr/wp-admin/
admin
L3kLb&KskuWlMat$*Ocz9m!3

**Comment by BenjaminSIP** [comment]
@thomas-ddev la vidéo est intégré via DIVI, est-ce qu'il est possible d'appliquer un délai de quelques second avant l'auto-play avec du code ?

Si pas possible, il faudrait refaire la section via un bloc HTML je pense et recréer la section hero from scratch.

@louberady en attendant si possible d'avoir les accès FTP du site s'il te plaît

**Comment by thomas-ddev** [comment]
J'ai regardé rapidement, mais j'ai l'impression qu'il n'y a pas de paramètres d'auto play qu'on peut désactiver dans un premier temps. Parce que c'est possible à faire notamment en JavaScript, le souci c'est que si le JS est chargé dans le footer, entre temps la vidéo aura potentiellement eu le temps de charger une seconde. Donc à voir

**Comment by thomas-ddev** [comment]
OK c'est bon, finalement j'ai pu apporter une solution, ça la stop dès qu'elle est présente sur la page, ça la relance 5 secondes plus tard, comme ça tout paraît plus fluide

**Comment by BenjaminSIP** [comment]
@louberady tu peux déjà voir le résultat mais si tu peux nous transmettre les accès FTP pour qu'on puisse appliquer les modifs proprement dans le code

**Comment by BenjaminSIP** [comment]
@thomas-ddev je te laisse voir pour cette demande supplémentaire

**Comment by thomas-ddev** [comment]
C'est fait

**Comment by louberady** [comment]
Accès FTP 
URL de co : ovh.com/auth
Id : sm105833
Mdp : AgaRad0829@

**Comment by BenjaminSIP** [comment]
@thomas-ddev si tu peux appliquer toutes les modifs de cette issue dans le code via les accès FTP puis supprimer le plugin d'ajout de scripts du site, merci

**Comment by thomas-ddev** [comment]
@louberady  @BenjaminSIP 

Ce n'est pas des accès FTP valides, il faut un nom d'hôte (pas une URL) ou une adresse IP. Sachant que ovh.com/auth c'est pour se connecter sur un compte OVH, mais même là ça ne fonctionne pas : 

![image](https://github.com/user-attachments/assets/1e7fda88-4c4b-4330-9d87-c5b675d20dc1)

**Comment by louberady** [comment]
PI : Mail à 14h53 pour informer la cliente, pas de réponse & relance sur WA à 18h, pas de réponse.

**Comment by louberady** [comment]
Bon..., merci pour l'info et les détails.
