### ISSUE TITLE
Mise en page FAQ + bas de page 

### ISSUE THREAD

**Issue by louberady** [wellsy-organization/projects#35]
Globalement sur **toutes les pages** il y a des problématiques de mise en page : 

- Dans les FAQ : manque beaucoup de retour à la ligne 
- Hors FAQ : les titres sont parfois bien trop grand
- J'aimerai que les sources soient toutes en italique + un peu espacé du reste du contenu SEO
- C'est plus rare, mais il arrive qu'il manque des MC en gras (balise bold)
- Parfois manque **un espace** ou **un point** entre 2 mots : exemple : 
 "Cela est dû à la présence de composés immunitaires qui stimulent nos défenses.Des effets bénéfiques pour le système digestif La santé intestinale est un pilier de notre bien-être général."

**Pages à vérifier :**

1. https://www.frenchmush.com/
2. https://www.frenchmush.com/collections/le-chaga
3. https://www.frenchmush.com/collections/le-cordyceps
4. https://www.frenchmush.com/collections/le-lions-mane
5. https://www.frenchmush.com/collections/le-reishi
6. https://www.frenchmush.com/products/le-chaga
7. https://www.frenchmush.com/products/le-chaga-la-poudre
8. https://www.frenchmush.com/products/le-cordyceps
9. https://www.frenchmush.com/products/le-cordyceps-poudre
10. https://www.frenchmush.com/products/le-lion-s-mane
11. https://www.frenchmush.com/products/le-lion-s-mane-poudre
12. https://www.frenchmush.com/products/le-reishi
13. https://www.frenchmush.com/products/le-reishi-poudre
14. https://www.frenchmush.com/collections/le-champignon-shiitake

--------------------------------------------------

Quelques illustrations des problématiques :

https://www.frenchmush.com/collections/le-chaga

<img width="1830" alt="Capture d’écran 2024-09-27 à 17 48 19" src="https://github.com/user-attachments/assets/cadf062a-5463-41b2-9ef6-f5d6ccdf7e58">

https://www.frenchmush.com/collections/le-cordyceps

Dans la FAQ :

<img width="1845" alt="Capture d’écran 2024-09-27 à 17 15 57" src="https://github.com/user-attachments/assets/128bde9f-0fda-484c-b31e-22fbf2a6801b">

<img width="1800" alt="Capture d’écran 2024-09-27 à 17 15 49" src="https://github.com/user-attachments/assets/0e4d921b-b56f-4788-ba21-6426603b4163">

https://www.frenchmush.com/products/le-chaga => exemple titres trop grand 

<img width="1797" alt="Capture d’écran 2024-09-27 à 17 33 40" src="https://github.com/user-attachments/assets/48cefd42-48cb-4d39-9a61-54036d2c4a84">

<img width="1872" alt="Capture d’écran 2024-09-27 à 17 33 44" src="https://github.com/user-attachments/assets/22d922cf-db86-47c2-9de1-03fa3d27d8c5">

https://www.frenchmush.com/products/le-chaga-la-poudre => exemple titres trop grand 

<img width="1915" alt="Capture d’écran 2024-09-27 à 17 39 53" src="https://github.com/user-attachments/assets/a0c7dfca-9c04-4164-93b2-09d2b1c7c067">

<img width="1844" alt="Capture d’écran 2024-09-27 à 17 39 58" src="https://github.com/user-attachments/assets/a8c001be-4386-405e-9d46-0e301624e887">

<img width="1876" alt="Capture d’écran 2024-09-27 à 17 40 05" src="https://github.com/user-attachments/assets/e64db9a7-e2e0-49e2-a0cb-6a3342aea67c">

https://www.frenchmush.com/collections/le-champignon-shiitake

<img width="1819" alt="Capture d’écran 2024-09-27 à 18 03 41" src="https://github.com/user-attachments/assets/c7ce21e4-0ff7-44b5-a844-3adc1b4be6e2">

-------------------------------------

Accès CMS :

https://accounts.shopify.com/login
[l.berady@see-u-better.com](mailto:l.berady@see-u-better.com)
DhfjgDSh34!unv45

**Comment by BenjaminSIP** [comment]
@thomas-ddev si tu peux effectuer cette issue, Pour les retours à la ligne, si possible de créer les retours à la ligne proprement (c'est à dire en faisant juste espace ou Shift + Espace dans l'éditeur et si ce sont les modules de FAQ qui ne le permettent pas de manière classique, peut être forcer les retours à la ligne avec des br par exemple et donner la méthodologie ici afin que @louberady sache comment créer des retours à la ligne en autonomie pour les prochains FAQ.

**Autres remarques :**
1) Il faudra bien vérifier toutes les pages mentionnées dans l'issue
2) C'est un site optimisé SEO donc pour rappel il faut bien faire attention à ne faire aucune action pouvant affecter le SEO (modification de Balises Hn ou modification de structure d'URL par exemple)

**Comment by thomas-ddev** [comment]
C'est parce que les FAQ sont gérés dans des fichiers .JSON custom du thème et il n'est pas autorisé de mettre des paragraphes ou des retours lignes <br/>, \n, etc. : 

![image](https://github.com/user-attachments/assets/0a560b5e-50e3-4cd6-ab40-db787cad9197)

La seule solution que j'ai trouvé, c'est d'entourer les paragraphes de <span>, seulement on ne peut pas leur mettre de classes non plus. Donc la seule solution sans changer tout le système, c'est utiliser des spans pour "entourer" chaque phrase, et en CSS je dit que les spans qui sont dans .mm-faq-text, sont un retour à la ligne.

Résultat pour un paragraphe : 
![image](https://github.com/user-attachments/assets/c9ae7225-e835-4eab-b442-9b650b478013)

Le souci c'est que du coup le code de ces fichiers ne permets pas de savoir où doivent avoir les retours à la ligne, puisqu'on peut mettre quasiment rien niveau code HTML. Donc je sais pas si je dois m'occuper de faire tous les textes de toutes les collections ? Parce que du coup c'est pas compliqué, mais ça reste long à faire, il faut modifier tous les fichiers comportant une FAQ et modifier chaque ligne pour y ajouter des <span>(texte ici)</span> où il faut un retour à la ligne : 
![image](https://github.com/user-attachments/assets/c9ee8256-81f0-4067-92ed-e9d26d0a9431)

**Comment by BenjaminSIP** [comment]
Est-ce qu'il n'existe pas un autre module qui gère les éléments en accordéon sur Shopify ?
@thomas-ddev ou @louberady ?

**Comment by louberady** [comment]
Mon alternant qui s'est en partie chargé de check ces FAQ (il y a 1 an) m'indique :

_pour les retours à la ligne c'est : "<\/br>" et oui les FAQ sont gérées dans le JSON car impossible à manipuler dans le back office de shopify_

Donc à ma connaissance, pas d'autres modules qui gère les FAQ.

**Comment by thomas-ddev** [comment]
Bonjour,

J'ai pu corriger proprement ce qui empêchait l'ajout de retours à la ligne. 

Voici l'explication : 

Avant toute chose, il est important de noter que "`</br>`" est une erreur de syntaxe. 
Les retours à la ligne en HTML ne peuvent s'écrire que de cette manière : 

- `"<br>"` (version courte) 
- `"<br />"` (version propre)

L'emplacement du "/" est très important, puisqu'on l'utilise en première position uniquement pour des balises qui peuvent être ouvertes et fermées plus tard, par exemple un paragraphe : `<p> Mon texte </p>`. Or, les retours à la ligne, ne peuvent pas s'écrire de la sorte : `<br> </br>`, "`</br>`" est donc une mauvais utilisation de la balise (même si les navigateurs comprennent cette version). 

C'est d'ailleurs parce que "`</br>`" n'existe pas en HTML, que cette variante était acceptée quand on modifiait le code des FAQ pour forcer des retours à la ligne (cf. https://github.com/wellsy-organization/projects/issues/35#issuecomment-2380593955).

En effet, le format des réponses des FAQ qui était utilisé, ne permettait pas les retours à la ligne, il y avait un filtre HTML qui l'empêchait (et `</br>` passe à la trappe, puisque c'est techniquement pas de l'HTML correct). 

Plutôt que d'utiliser une mauvaise syntaxe HTML, j'ai donc préféré chercher la cause et corriger cela, sachant que ça empêchait l'utilisation d'autres balises HTML qui pourraient être utiles, comme les listes à puces.

Le souci est que le type de réponse était au format Shopify "inline_richtext", ce format n'accepte pas les retours à la ligne (d'où le "inline") : 
![image](https://github.com/user-attachments/assets/a74b81e8-f14a-4c9d-aaa4-160ba5ab9966)

Pour corriger cela, je l'ai donc passé en "richtext", ce qui autorise davantage de balises HTML, donc les retours à la ligne/paragraphes : 
![image](https://github.com/user-attachments/assets/7e2d934f-7226-4eb7-93b0-56ab961bf5c7)

Désormais, @louberady il est possible de modifier facilement dans le personnalisateur de thème Shopify, les réponses des FAQ, tout en y ajoutant le formatage souhaité : 
![image](https://github.com/user-attachments/assets/b27cb612-e828-4d19-ae09-00848f28d9a6)

J'ai par exemple ici modifié la collection Chaga (https://www.frenchmush.com/collections/le-chaga). 

Je laisse éventuellement corriger les autres endroits, ne sachant pas constamment où les retours à la ligne doivent être effectués. Avec de la chance un simple copier-coller du document source pourrait suffire à conserver tout l'HTML.

**Comment by BenjaminSIP** [comment]
En résumé @louberady, le problème technique a été corrigé, si vous pouvez vous occuper de faire les modifications sur chaque page pour éviter que l'on passe trop de temps sur cette issue

**Comment by louberady** [comment]
@BenjaminSIP Possible d'exporter en **PDF** toute l'issue ? Que je la partage à mon alternant pour qu'il s'en charge.
@thomas-ddev Merci Thomas ! J'avance enfin sur ce sujet. 🚀

**Comment by BenjaminSIP** [comment]
Clic droit puis "Imprimer", puis télécharger en PDF, mis à part ça je ne pense pas que ce soit possible

**Comment by louberady** [comment]
Parfait ça fonctionne merci !

**Comment by BenjaminSIP** [comment]
@louberady je te laisse passer en Done quand ça te semblera bon

**Comment by louberady** [comment]
@BenjaminSIP 
J'étais encore en A/R avec mon alternant Mourad sur le sujet, d'où mon retour tardif. :)
Pour les pages **/collections** c'est good.

Il reste juste un point non traité et qui est présent sur toutes les page **/products**
=> Hors FAQ : les titres sont bien trop grand 
Mourad a tenté de résoudre le problème sans succès.

- https://www.frenchmush.com/products/le-chaga
- https://www.frenchmush.com/products/le-chaga-la-poudre
- https://www.frenchmush.com/products/le-cordyceps
- https://www.frenchmush.com/products/le-cordyceps-poudre
- https://www.frenchmush.com/products/le-lion-s-mane
- https://www.frenchmush.com/products/le-lion-s-mane-poudre
- https://www.frenchmush.com/products/le-reishi
- https://www.frenchmush.com/products/le-reishi-poudre

**Comment by BenjaminSIP** [comment]
@thomas-ddev si tu peux voir ce dernier point également s'il te plaît

**Comment by louberady** [comment]
@thomas-ddev oui c'est ça, je suppose que ce sont tous des h2 ? 
Peut on faire en sorte que les h2 des contenus SEO ⬇️ soit plus petit en taille de police ? 

![Image](https://github.com/user-attachments/assets/7c74c6a5-f513-4afd-8ee5-8fea6ff07093)

**Comment by thomas-ddev** [comment]
OK tout a été globalement réduit

**Comment by louberady** [comment]
Super merci

**Comment by louberady** [comment]
Dernière question si je souhaite créer des saut de ligne sur des pages produits (hors FAQ)
je dois ajouter tout simplement des ⬇️ c'est ça ? 
![Image](https://github.com/user-attachments/assets/180213b3-3919-4509-a9b5-9b901c615906)

**Comment by BenjaminSIP** [comment]
Oui sans les guillemets
