### ISSUE TITLE
Lots intelligents

### ISSUE THREAD

**Issue by BenjaminSIP** [wellsy-organization/projects#44]
**Brief client :**
En essayant de créer un produit composé (lot intelligent) regroupant les références 26934, 1514, 23324 et 1158 sous le produit 233242, je n'ai pas réussi à y intégrer les références 26934 et 23324. C'est la première fois que je ne parviens pas à enregistrer un produit dans un produit composé.

**Comment by thomas-ddev** [comment]
Parce que par exemple "23324" corresponds à un produit variable, donc comportant des variations : 
![image](https://github.com/user-attachments/assets/ec1f6fa2-d8a5-4334-a8a9-a67a55df6555)

Il faut donc choisir la référence qui est indiquée dans les variations du produit variable que l'on souhaite ajouter :

![image](https://github.com/user-attachments/assets/bc429496-dda9-4ed4-8d0e-328cc4de32cb)
