### ISSUE TITLE
Faire correspondre images aux conteners - page blog

### ISSUE THREAD

**Issue by Kantin-digitalmarketing** [wellsy-organization/projects#7]
Page blog novaptech : https://novaptech.com/en/aptamer-news/ 

La cliente ne met pas ses images au même format, donc les images ne remplissent pas toutes leur conteneurs. Ajouter du code pour forcer les images à s'étirer.

**Comment by BenjaminSIP** [comment]
Salut @louberady,

Si tu peux me préciser exactement ce qui ne va pas, car on ne peut pas mieux faire, le images sont bien centrées horizontalement et verticalement et prennent 100% de la hauteur et de la largeur.

Les images ayant toutes des tailles différentes, on ne peut vraiment pas mieux faire.

Sur tes captures sinon :
Première capture, c’est l’image elle-même qui a des bordures blanches, je te laisse vérifier le lien de l’image en question :  https://novaptech.com/wp-content/uploads/2024/06/65e9c6a88daab615254560.png
 
Deuxième capture, quel est le souci ?

**Comment by louberady** [comment]
La problématique est que sur son ancien site, les images se placent correctement sur la section blog.
soit ici : https://novaptech.com/en/aptamer-news/

exemple concret *1 : [Novaptech: new offices!](https://novaptech.com/en/novaptech-new-offices/)
July 4, 2024
* si tu visualises l'image de mise en avant les personnes en haut à droite sont coupés

exemple concret *2 : [Novaptech is coming to Barcelona!BIO-Europe Spring 2024](https://novaptech.com/en/bio-europe-barcelona/)
March 7, 2024
* coupé à droite, coupé à gauche

exemple concret *3 : [Novaptech at the Bio-Europe Spring](https://novaptech.com/en/novaptech-bio-europe-spring/)
March 13, 2023
* coupé à droite, coupé à gauche

**Comment by BenjaminSIP** [comment]
J'ai bien compris le soucis, mais on ne peut pas faire autrement, c'est impossible que sur son ancien site on voyait la totalité des images, à moins que chaque container avait des tailles complètement différentes entre eux

**Comment by BenjaminSIP** [comment]
Je te mets 2 exemples d'images qui n'ont pas du tout le même format :
https://novaptech.com/wp-content/uploads/2024/06/640f4ba67f1e4784209360.jpg
https://novaptech.com/wp-content/uploads/2024/06/627526484e1f1673022641.jpg

Ces 2 formats ne peuvent pas remplir la totalité du container en hauteur et en largeur sans couper l'image OU sans que les containers adoptent des formats différents en fonction de chaque image.

**Comment by louberady** [comment]
Ok si ce n'est pas possible avec du code, Kantin m'avait émis cette possibilité. 
Je vais tenter de re dimensionner les images pour voir si ça passe.
Merci

**Comment by BenjaminSIP** [comment]
Ok si ce n'est pas possible avec du code, Kantin m'avait émis cette possibilité.
-> Le code a déjà été appliqué justement par combler les espaces.

Je vais tenter de re dimensionner les images pour voir si ça passe.
-> D'accord
